### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/basis#33] opened 2016-08-06 18:56 UTC
Can not install it from /admin/modules/install

Details

LOCATION http://domain.com/batch?id=5&op=do_nojs&op=do

REFERRER http://domain.com/batch?op=start&id=5

"There was an error while installing Basis. Cannot extract temporary://update-cache-e381e819/1.x-0.0.1, not a valid archive."

**Comment by wesruv** [comment] 2016-08-06 21:12
Hrmm.... I'll give it a shot on my local and see if I can sort something out.

**Comment by bd0bd** [comment] 2016-08-07 06:07
Of cause I can install it directly via FTP.

**Comment by wesruv** [comment] 2016-08-21 16:22
Ahh, I think this because it's supposed to be installed from: `/admin/appearance/install`

It shouldn't (and didn't for me) show up in the modules listing. Can you check to see if this is addressed now?

**Comment by bd0bd** [comment] 2016-08-21 17:01
Basis is listed there but if I try to install from

`/admin/appearance/install`

I get

There was an error while installing Basis. Cannot extract temporary://update-cache-3617a4af/1.x-0.0.1, not a valid archive.

**Comment by bd0bd** [comment] 2016-08-21 17:08
Now Basis is NOT listed at `/admin/modules/install`

**Comment by klonos** [comment] 2016-08-22 09:55
> I get
> 
> There was an error while installing Basis. Cannot extract temporary://update-cache-3617a4af/1.x-0.0.1, not a valid archive.

Same here:

There was an error while installing Basis. Cannot extract temporary://update-cache-997259df/1.x-0.0.1, not a valid archive.

Not sure, but this might be a core issue because after the error I get redirected to `/admin/modules/install` (??).

> Now Basis is NOT listed at `/admin/modules/install`

It shouldn't. It's a theme - not a module.

**Comment by klonos** [comment] 2016-08-22 09:57
> ...this might be a core issue...

I guess not because if I add another theme in the queue, that one gets installed while Basis still fails. Packaging issue then? @quicksketch ? @Gormartsen ?

**Comment by bd0bd** [comment] 2016-08-23 14:49
```
It shouldn't. It's a theme - not a module.
```

I know. I thought **wesruv** has asked me to check it:

```
Can you check to see if this is addressed now?
```

May be I have misunderstood him.

**Comment by wesruv** [comment] 2016-08-25 17:31
@bd0bd nope, I'm glad you checked to see if it was still showing up in modules :smile: 

I'm also getting this issue and I feel out of my depth for fixing it.

```
There was an error while installing Basis. Cannot extract temporary://update-cache-c8895f56/1.x-0.0.2, not a valid archive.
```

**Comment by jenlampton** [comment] 2016-08-25 18:37
I'm getting the same error. It looks like it's trying to extract something that's not a .zip archive. Does this happen for other themes, or just Basis?

**Comment by jenlampton** [comment] 2016-08-25 18:39
I'm having the same problem with bootstrap_lite. Perhaps a bug in the installer?  I will open an issue against core and we can work on this there.

**Comment by quicksketch** [comment] 2016-08-25 19:14
I could reproduce this also. It seems that the problem is that the temporary file is located at `temporary://update-cache-a8bb2488/1.x-0.0.2`, and is missing the extension `.zip`. So without the extension, Backdrop doesn't know what format the archive file is. I'll keep checking and see if this is a Backdrop core issue or a packager issue.

**Comment by quicksketch** [comment] 2016-08-25 19:32
So it looks like this is a packager problem. When I visit the release page for Basis, I can see that a package was created correctly:

Release: https://github.com/backdrop-contrib/basis/releases/tag/1.x-0.0.2
Package: https://github.com/backdrop-contrib/basis/releases/download/1.x-0.0.2/basis.zip

But when I visit the release page on BackdropCMS.org, it's pointing at the wrong zip file:

Release: https://backdropcms.org/project/basis
Package: https://github.com/backdrop-contrib/basis/archive/1.x-0.0.2.zip

So the problem is just that BackdropCMS.org is using the wrong URL to the zip files. The good news is this means we can fix the problem across the board by fixing BackdropCMS.org, then the installer will start working again.

**Comment by quicksketch** [comment] 2016-08-26 02:18
I've fixed this issue on BackdropCMS.org. I've now been able to install Basis through the Project Installer interface from my localhost Backdrop site.

The following additional packages also had incorrect links:

```
https://api.github.com/repos/backdrop-contrib/githubapi/zipball/1.x-1.0.3         
https://api.github.com/repos/backdrop-contrib/githubapi/zipball/1.x-1.0.4         
https://api.github.com/repos/backdrop-contrib/project/zipball/1.x-1.0.0-beta7     
https://api.github.com/repos/backdrop-contrib/seo_meta/zipball/1.x-1.0.3          
https://api.github.com/repos/backdrop-contrib/session_limit/zipball/1.x-1.0.0     
https://api.github.com/repos/backdrop-contrib/ejectorseat/zipball/1.x-1.0.0       
https://api.github.com/repos/backdrop-contrib/ejectorseat/zipball/1.x-1.0.1       
https://api.github.com/repos/backdrop-contrib/session_expire/zipball/1.x-1.0.0    
https://api.github.com/repos/backdrop-contrib/bot_repellent/zipball/1.x-1.0.2     
https://api.github.com/repos/backdrop-contrib/r4032login/zipball/1.x-1.0.1        
https://api.github.com/repos/backdrop-contrib/ejectorseat/zipball/1.x-1.0.2       
https://api.github.com/repos/backdrop-contrib/site_verification/zipball/1.x-1.0.1 
https://api.github.com/repos/backdrop-contrib/session_limit/zipball/1.x-1.0.1     
https://api.github.com/repos/backdrop-contrib/session_expire/zipball/1.x-1.0.1    
https://api.github.com/repos/backdrop-contrib/robotstxt/zipball/1.x-1.0.1         
https://api.github.com/repos/backdrop-contrib/smtp/zipball/1.x-1.3.1              
https://api.github.com/repos/backdrop-contrib/seo_meta/zipball/1.x-1.0.4          
https://api.github.com/repos/backdrop-contrib/easy_xmlsitemap/zipball/1.x-1.0.1   
https://api.github.com/repos/backdrop/backdrop/zipball/1.4.4                      
https://api.github.com/repos/backdrop-contrib/easy_xmlsitemap/zipball/1.x-1.0.2   
https://api.github.com/repos/backdrop-contrib/githubapi/zipball/1.x-1.0.5         
https://api.github.com/repos/backdrop-contrib/previous_login/zipball/1.x-1.0.1    
```

These have all been fixed on BackdropCMS.org, and the new updates will prevent this from happening on new releases of both modules and themes.

**Comment by jenlampton** [comment] 2016-08-26 02:26
Fantastic, thanks @quicksketch!  Do you want to leave an update on the core issue? https://github.com/backdrop/backdrop-issues/issues/2095

**Closed as completed** 2016-08-26 02:26 UTC
Labels: help wanted

**Comment by quicksketch** [comment] 2016-08-26 02:54
Thanks, good idea. I closed that issue and pointed to the update in the BackdropCMS.org issue queue where this issue was introduced: https://github.com/backdrop-ops/backdropcms.org/issues/264#issuecomment-242613068.

**Comment by klonos** [comment] 2016-08-27 05:52
Thanx you guys! 👍
