### ISSUE TITLE
Layout problem on iPad

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/basis#35] opened 2016-08-15 14:45 UTC
@wesruv I am not normally an iPad user and this morning was disturbed to see a problem with Basis and layout Moscone whilst working on a new site with a client. What was happening was that the content of the side column was not being displayed below the main content, as it should, either in portrait or landscape mode. Instead there seemed just to be a blank area. This happened when using either the default (Safari) or the Chrome browser.

The layout is working fine on an Android tablet, and on a Mac.

I shall try and borrow an iPad to do some more testing but wonder whether anyone else has seen this behaviour.

**Comment by Graham-72** [comment] 2016-08-16 14:35
I have now been able to check Jen's test page http://www.jenlampton.com/moscone on an iPad and the login and sidebar are not being displayed. So we have a layout problem, though at the moment I don't know what version iPad it is or whether this makes a difference.

I have added a mention of this at https://github.com/backdrop/backdrop-issues/issues/1985

**Comment by jenlampton** [comment] 2016-08-16 21:42
This is a duplicate of https://github.com/backdrop/backdrop-issues/issues/1985. It should be fixed in 1.4.4, as that fix has been committed.

**Closed as completed by jenlampton** 2016-08-16 21:42 UTC
Labels: duplicate
